#!/usr/bin/env python3
"""Generate docs/security/endpoint-authorization-matrix.md from ROUTE_AUTHZ.

The matrix was maintained by hand and drifted: it listed chat, memories, retention,
consent, traces, evidence and evals as permission-protected while only audit, tenant
metrics and detailed worker health actually checked anything. Documentation ahead of
runtime is the failure this repository keeps closing, so the table is now derived
from the same declarations the enumeration guard enforces.

Enforced, Planned and Public are rendered separately, and the Planned section says
plainly that it is not a control.

    python scripts/generate_authz_matrix.py            # rewrite
    python scripts/generate_authz_matrix.py --check    # exit 1 on drift (CI gate)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "services" / "api"))

OUTPUT = REPO_ROOT / "docs" / "security" / "endpoint-authorization-matrix.md"
MARKER_START = "<!-- BEGIN GENERATED MATRIX -->"
MARKER_END = "<!-- END GENERATED MATRIX -->"


def _permission_cell(spec) -> str:
    if spec.self_permission or spec.tenant_permission:
        parts = []
        if spec.self_permission:
            parts.append(f"`{spec.self_permission.value}` (own)")
        if spec.tenant_permission:
            parts.append(f"`{spec.tenant_permission.value}` (tenant)")
        return " / ".join(parts)
    if spec.permission:
        return f"`{spec.permission.value}`"
    return "— *(any authenticated principal)*" if spec.scope.value != "public" else "— *(public)*"


def render() -> str:
    from app.auth.authz_spec import ROUTE_AUTHZ, Status

    def table(entries) -> str:
        if not entries:
            return "_(none)_\n"
        lines = ["| Method | Path | Scope | Permission | Note |", "| --- | --- | --- | --- | --- |"]
        for (method, path), spec in entries:
            note = spec.note.replace("\n", " ") if spec.note else ""
            lines.append(
                f"| `{method}` | `{path}` | {spec.scope.value} | "
                f"{_permission_cell(spec)} | {note} |"
            )
        return "\n".join(lines) + "\n"

    ordered = sorted(ROUTE_AUTHZ.items(), key=lambda kv: (kv[0][1], kv[0][0]))
    enforced = [e for e in ordered if e[1].status is Status.ENFORCED]
    planned = [e for e in ordered if e[1].status is Status.PLANNED]
    public = [e for e in ordered if e[1].status is Status.PUBLIC]

    return f"""{MARKER_START}
<!-- Generated by scripts/generate_authz_matrix.py — do not edit this block. -->

### Enforced

The handler checks the permission. {len(enforced)} of {len(ordered)} routes.

{table(enforced)}
### Planned — declared, **not yet enforced**

The contract is agreed and the enumeration guard holds these routes to it, but the
handler does not check the permission yet. **Do not rely on this section as a
control.**

{table(planned)}
### Public

Unauthenticated by design. These must expose no tenant or user identifiers.

{table(public)}
{MARKER_END}"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 on drift")
    args = parser.parse_args()

    generated = render()
    current = OUTPUT.read_text()

    if MARKER_START not in current:
        raise SystemExit(f"{OUTPUT} has no generated block; add {MARKER_START}/{MARKER_END}")

    start = current.index(MARKER_START)
    end = current.index(MARKER_END) + len(MARKER_END)
    updated = current[:start] + generated + current[end:]

    if updated == current:
        print("✓ authorization matrix matches ROUTE_AUTHZ")
        return 0
    if args.check:
        print(
            "Authorization matrix drift: docs/security/endpoint-authorization-matrix.md\n"
            "no longer matches ROUTE_AUTHZ.\n\n"
            "    python scripts/generate_authz_matrix.py\n",
            file=sys.stderr,
        )
        return 1
    OUTPUT.write_text(updated)
    print(f"✓ wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
